#!/bin/env bash

# INFO: you can test the result of script using following command
# ./halo --nama Budi --kota Malang
# you can convert to uppercase using tr command or ${variable^^}

# WARN: DON'T EDIT THIS BLOCK
while [[ $# -gt 0 ]]; do
  case $1 in
  --nama)
    nama="$2"
    shift 2
    ;;
  --kota)
    kota="$2"
    shift 2
    ;;
  *)
    echo "Opsi tidak diketahui $1"
    exit 1
    ;;
  esac
done

# TODO: ADD VALIDATION
# TODO: CONVERT TO UPPERCASE
