#!/bin/env bash

# INFO: You can test the result of script using following command
# echo "16" | ./kategori_usia

# Read expression from stdin
read usia

# WARN: NEVER EDIT THIS BLOCK
if ! [[ "$usia" =~ ^[0-9]+$ ]]; then
  echo "Input tidak valid"
  exit 1
fi

# TODO: ADD LOGIC AFTER THIS LINE
