#!/bin/env bash

# INFO: You can test the result of script using following command
# echo "Test123" | ./validasi_password
# INFO: You can validate password using regex pattern
# Example:
# match for lower alphabetic characters
# if [[ $pattern =~ [a-z] ]];
# fi

# Membaca password dari input standar (stdin)
read password

# TODO: ADD LOGIC AFTER THIS LINE
