#!/bin/env bash

# HINT: You can test the result of script using following command
# echo "Test123" | ./validasi_password

# Membaca password dari input standar (stdin)
read password

# Inisialisasi flag valid
is_valid=true

# Cek panjang minimal 8 karakter
if [ ${#password} -lt 8 ]; then
  echo "Password terlalu pendek"
  is_valid=false
fi

# Cek mengandung huruf kapital
if ! [[ $password =~ [A-Z] ]]; then
  echo "Password harus mengandung huruf kapital"
  is_valid=false
fi

# Cek mengandung angka
if ! [[ $password =~ [0-9] ]]; then
  echo "Password harus mengandung angka"
  is_valid=false
fi

# Jika semua validasi lolos
if $is_valid; then
  echo "Password diterima"
fi
