name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Halo Without Parameter
      id: halo-without-parameter
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Halo Without Parameter
        setup-command: ''
        command: "./halo"
        input: ''
        expected-output: |
          Error: Parameter --nama wajib diisi.
          Error: Parameter --kota wajib diisi.
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Halo Without City Parameter
      id: halo-without-city-parameter
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Halo Without City Parameter
        setup-command: ''
        command: "./halo"
        input: '--nama Budi'
        expected-output: |
          Error: Parameter --kota wajib diisi.
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Halo Without Name Parameter
      id: halo-without-name-parameter
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Halo Without Name Parameter
        setup-command: ''
        command: "./halo"
        input: '--kota Malang'
        expected-output: |
          Error: Parameter --nama wajib diisi.
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Halo Valid Parameter
      id: halo-valid-parameter
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Halo Valid Parameter
        setup-command: ''
        command: "./halo"
        input: '--nama Budi --kota Malang'
        expected-output: "SELAMAT DATANG BUDI DARI KOTA MALANG"
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Child Age Category
      id: child-age-category
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Child Age Category
        setup-command: ''
        command: "./kategori_usia"
        input: "0"
        expected-output: "Kategori: Anak-anak"
        comparison-method: exact
        timeout: 10
        max-score: 5
        
    - name: Teen Age Category
      id: teen-age-category
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Teen Age Category
        setup-command: ''
        command: "./kategori_usia"
        input: "13"
        expected-output: 'Kategori: Remaja'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Adult Age Category
      id: adult-age-category
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Adult Age Category
        setup-command: ''
        command: "./kategori_usia"
        input: "59"
        expected-output: 'Kategori: Dewasa'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Elderly Age Category
      id: elderly-age-category
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Elderly Age Category
        setup-command: ''
        command: "./kategori_usia"
        input: "60"
        expected-output: 'Kategori: Lansia'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Password Too Short
      id: password-too-short
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Password Too Short
        setup-command: ''
        command: "./validasi_password"
        input: "Pass123"
        expected-output: 'Password terlalu pendek'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Password All Lowercase
      id: password-all-lowercase
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Password All Lowercase
        setup-command: ''
        command: "./validasi_password"
        input: "pass12345"
        expected-output: 'Password harus mengandung huruf kapital'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Password Not Have Number
      id: password-not-have-number
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Password Not Have Number
        setup-command: ''
        command: "./validasi_password"
        input: "KataSandi"
        expected-output: 'Password harus mengandung angka'
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Password Not Valid
      id: password-not-valid
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Password Not Valid
        setup-command: ''
        command: "./validasi_password"
        input: "sandi"
        expected-output: |
          Password terlalu pendek
          Password harus mengandung huruf kapital
          Password harus mengandung angka
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Password Valid
      id: password-valid
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Password Valid
        setup-command: ''
        command: ./validasi_password
        input: Pass1234
        expected-output: |
          Password diterima
        comparison-method: exact
        timeout: 10
        max-score: 5

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HALO-WITHOUT-PARAMETER_RESULTS: "${{steps.halo-without-parameter.outputs.result}}"
        HALO-WITHOUT-CITY-PARAMETER_RESULTS: "${{steps.halo-without-city-parameter.outputs.result}}"
        HALO-WITHOUT-NAME-PARAMETER_RESULTS: "${{steps.halo-without-name-parameter.outputs.result}}"
        HALO-VALID-PARAMETER_RESULTS: "${{steps.halo-valid-parameter.outputs.result}}"
        CHILD-AGE-CATEGORY_RESULTS: "${{steps.child-age-category.outputs.result}}"
        TEEN-AGE-CATEGORY_RESULTS: "${{steps.teen-age-category.outputs.result}}"
        ADULT-AGE-CATEGORY_RESULTS: "${{steps.adult-age-category.outputs.result}}"
        ELDERLY-AGE-CATEGORY_RESULTS: "${{steps.elderly-age-category.outputs.result}}"
        PASSWORD-TOO-SHORT_RESULTS: "${{steps.password-too-short.outputs.result}}"
        PASSWORD-ALL-LOWERCASE_RESULTS: "${{steps.password-all-lowercase.outputs.result}}"
        PASSWORD-NOT-HAVE-NUMBER_RESULTS: "${{steps.password-not-have-number.outputs.result}}"
        PASSWORD-NOT-VALID_RESULTS: "${{steps.password-not-valid.outputs.result}}"
        PASSWORD-VALID_RESULTS: "${{steps.password-valid.outputs.result}}"
      with:
        runners: >
          halo-without-name-parameter,
          halo-without-city-parameter,
          halo-without-name-parameter,
          halo-valid-parameter,
          child-age-category,
          teen-age-category,
          adult-age-category,
          elderly-age-category,
          password-too-short,
          password-all-lowercase,
          password-not-have-number,
          password-not-valid,
          password-valid
